### ISSUE TITLE
Возможно этот эффект получается если на врага упадёт копия пока он будет притягиваться с помощью W земели

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#107]
![image](https://user-images.githubusercontent.com/29237955/27832596-e4d792f8-60d7-11e7-8d4e-a0cbbced8381.png)
P.S. смотреть на врку

**Comment by DoctorGester** [comment]
https://clips.twitch.tv/GiantInspiringCoyotePupper
