### ISSUE TITLE
Серые цифры для урона по щиту

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#115]

**Comment by DoctorGester** [comment]
What about when damage went through the shield (WK R into LC W)

**Comment by C039ATeJL** [comment]
серая цифра "2" и красная цифра "2"
Почему нет?

**Comment by DoctorGester** [comment]
1 instance of damage

**Comment by C039ATeJL** [comment]
Тогда сделать ещё один цвет, означающий что урон прошел сквозь щит и уменьшился?

**Comment by DoctorGester** [comment]
Don't really see much value in that currently. I might think of something else.
