### ISSUE TITLE
Venge R armor reduction aura doesn't work on rune(dublicate)

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#118]
Зачем я сделал дубликат?
1. На первое issue(https://github.com/DoctorGester/crumbling-island-arena/issues/26) был повешен фильтр "bug".
2. Оно было закрыто с комментарием "not confirmed"(не подтверждено) от Mahou.
В этот раз я прикрепляю пруфы
![sven2](https://user-images.githubusercontent.com/29237955/27930796-94c211ce-62a0-11e7-83df-ba4cd7fe50b3.gif)

**Comment by C039ATeJL** [comment]
Оно вообще на суммоны вроде не работает

**Comment by DoctorGester** [comment]
I closed the wrong one by accident I think.
