### ISSUE TITLE
CIA 1.0 

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#122]
Если от CIA 1.0 остался код можно немного доработать и сделать новый режим игры или отдельную кастомку

**Comment by DoctorGester** [comment]
В репозитории можно вернуться в любой момент по истории кода. Новый режим сделать из этого просто физически я один не потяну да и не хочу, отдельную кастомку - придется фиксить баги, которые появились в доте, если кто-то хочет - он может это сделать.
