### ISSUE TITLE
Invo active EMP doesn't blow up on enemies already casting or channeling spells

### ISSUE THREAD

**Issue by vocalpocal** [DoctorGester/crumbling-island-arena#127]
eg Zeus Q has a relatively long cast time, if Zeus starts casting Q just before EMP activates, he gets the Q casted

**Comment by vocalpocal** [comment]
Why is this listed as an enhancement? 🤔 It is just as much bug as the old interaction with m1 animation and disarm imo

**Comment by DoctorGester** [comment]
It's more of a feature since it wasn't originally intended I think
