### ISSUE TITLE
После долгой паузы сообщения в чате не отображаются(для других игроков)

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#135]

**Comment by DoctorGester** [comment]
Не очень понял, можно подробнее описание того, что происходит?

**Comment by C039ATeJL** [comment]
1. Открывается окно пика персонажей для 1 раунда
2. Ты(или кто-либо другой) пишешь туда сообщение
3. Во время игры это сообщение не будет отображаться в чате
![image](https://user-images.githubusercontent.com/29237955/28280219-bb6382a2-6b2b-11e7-8930-ba05932462e4.png)
![image](https://user-images.githubusercontent.com/29237955/28280239-c4fc0276-6b2b-11e7-99fe-8e35afabca3b.png)
Работает только в пике перед 1 раундом
Сообщение будет отображаться, когда вы будете выбирать героев в последующих пиках

**Comment by C039ATeJL** [comment]
1. Долгая пауза(5 минут или что-то в этом роже)
2. Пишешь сообщения, ты их видишь, но другие игроки-нет.
