### ISSUE TITLE
Акс не имеет имени, а имя войда(Eyes of heaven) не переведено на русский

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#147]
Bug. High priority.
![image](https://user-images.githubusercontent.com/29237955/28463495-54140e36-6e29-11e7-8d1f-7eab2a056e27.png)
![image](https://user-images.githubusercontent.com/29237955/28463503-5df34458-6e29-11e7-8a3c-4a1728d15655.png)

**Comment by 13lackHawk** [comment]
Акса и Войда нет в игре - вот это реально баг и хай приорити.
