### ISSUE TITLE
Убрать вот эти палочки

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#154]
![image](https://user-images.githubusercontent.com/29237955/28539757-817b96e8-70bb-11e7-9685-03ebfa2cfba4.png)

**Comment by 13lackHawk** [comment]
??

**Comment by C039ATeJL** [comment]
Хз, как по мне они бесполезны

**Comment by DoctorGester** [comment]
They are ok
