### ISSUE TITLE
Убрать возможность наносить 2 урона M1 и блинком зевса через стену

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#165]
К-кликбейт

Имею ввиду чтоб убрать возможность наносить 2 урона когда сама М1 зевса не прошла сквозь стену, но была в нужном радиусе(те когда враг закрывает собой стену). Так же с блинком.

**Comment by DoctorGester** [comment]
I agree that this makes sense in terms of logic but I don't want to add more complicated rules to these abilities
