### ISSUE TITLE
Drow Q debuff icon isn't visible

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#166]
![image](https://user-images.githubusercontent.com/29237955/28681317-bed93368-7301-11e7-9e29-c494659326c1.png)
По крайней мере в Spectators mode

**Comment by DoctorGester** [comment]
I can't test that. Please close the issue if it works in normal mode, spectator mode is very low priority.

**Comment by C039ATeJL** [comment]
Иконка в обычной игре также не отображается
![image](https://user-images.githubusercontent.com/29237955/28724639-615cbfc6-73c3-11e7-89cf-7a12e5a02e81.png)
