### ISSUE TITLE
Падения на большой скорости

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#170]
Развивая большую скорость герой может передвигаться над ямами, но падает странным и нестественным образом когда останавливается

**Comment by DoctorGester** [comment]
Any example?

**Comment by C039ATeJL** [comment]
Пруфов нет, ибо появляется редко и у меня не работает песочница.

Самым лёгким примером думаю является земеля. Используя w на весь радиус может развить достаточную скорость. Возможно для этого подходят не все дыры, а только меньшие.
Также в этом issue описывается именно этот баг https://github.com/DoctorGester/crumbling-island-arena/issues/90
