### ISSUE TITLE
Add 0-2 randomly placed techies bombs each round which explode on hit and deal 3 damage in an area

### ISSUE THREAD

**Issue by DoctorGester** [DoctorGester/crumbling-island-arena#175]

**Comment by C039ATeJL** [comment]
1. Рандом-такое. Думаю было бы лучше:
1) Увеличить кол-во мин и убрать фактор рандома.
2) Уменьшить урон до 2(тк мин будет больше).
2. Думаю логично, что они будут нейтральными(наносить урон всем, не зависимо от того кто её взорвал), и тогда, уверен будет много неразберихи(багов, не будет понятно как это работает). Устраняется более подробным описанием и тестами в CIA Test.
3. Как по мне они должны также влиять на землю(ломать ближе к эпицентру взрыва и повреждать землю, которая находиться относительно далеко). Это не прописано в названии, хотя, думаю, так и задумывалось.
4. Это даст преимущество ренж героям, соответственно, нужно понерфить метовых.
