### ISSUE TITLE
Implement ranked season 14 reward

### ISSUE THREAD

**Issue by DoctorGester** [DoctorGester/crumbling-island-arena#177]
Suggestions are welcome

#81 previous season suggestions for reference

**Comment by 13lackHawk** [comment]
Tusk Rework = Tusk Set
https://dota2.gamepedia.com/Barrier_Rogue

Slark Rework = Slark... ehm there is no good sets for Slark to be honest. But he has a lot of awesome weapons which can be implemented in game.
https://dota2.gamepedia.com/Hydrakan_Latch + Golden edition for top3 ranked14 season(?)
https://dota2.gamepedia.com/Pale_Edge + https://dota2.gamepedia.com/Gilded_Edge for top3 ranked14(?)
But if you really want a set anyway then I would recommend this:
https://dota2.gamepedia.com/Deep_Sea_Scoundrel
In this set with this muzzle and chains he looks like real Hanged Man.

**Comment by mindalek** [comment]
Lc https://dota2.gamepedia.com/The_Gifts_of_Zhuzhou 
or
Gyro https://dota2.gamepedia.com/Mechalodon_Interdictor
or 
TA https://dota2.gamepedia.com/Province_of_the_Psion_Inquisitor

**Comment by C039ATeJL** [comment]
LC: https://dota2.gamepedia.com/Blades_of_Voth_Domosh + https://dota2.gamepedia.com/Baneful_Devotion + флаги
LC: The Bronze Legion Vanguard(вроде как можно добавлять предметы из мастерской, как было с зомбёй)

**Comment by C039ATeJL** [comment]
Sniper: https://dota2.gamepedia.com/Occultist%27s_Pursuit
