### ISSUE TITLE
Windranger Haste should make her phased

### ISSUE THREAD

**Issue by DoctorGester** [DoctorGester/crumbling-island-arena#194]

**Comment by C039ATeJL** [comment]
?

**Comment by vocalpocal** [comment]
Sounds really strong, What if her E phased her instead?

**Comment by DoctorGester** [comment]
Not through trees, just through units.

**Comment by vocalpocal** [comment]
Would it then make any difference except versus WK?

**Comment by DoctorGester** [comment]
Can give an edge in narrow points when you are bodyblocked. It's not meant to be a huge change.

**Comment by vocalpocal** [comment]
Well WR could use a small buff since her Q is pretty bad
