### ISSUE TITLE
Scoreboard damage dealt bugged

### ISSUE THREAD

**Issue by vocalpocal** [DoctorGester/crumbling-island-arena#207]
Sometimes shows too little damage.
Need confirmation: Scoreboard doesn't count amplified damage (Break, invoker ethereal etc)
EDIT: CONFIRMED

**Comment by vocalpocal** [comment]
![20170808203052_1](https://user-images.githubusercontent.com/25270027/29085664-9ca95bb2-7c78-11e7-9471-52c093a66725.jpg)
Confirmed with Venge R and basic attacks only (one basic attack hit without being Break boosted, so it is 11 instead of 10)

**Comment by C039ATeJL** [comment]
appeal if you need a help :+1:
