### ISSUE TITLE
Rework mines spawn mechanism

### ISSUE THREAD

**Issue by 13lackHawk** [DoctorGester/crumbling-island-arena#211]
Spawn only even(2,4,6...) or zero number of mines any round(always at least 2 mines in 3v3).
- At least one mine should be near both teams.
For example: mechanism choose to spawn 4 mines, then there should be 2 mines near trees close to the red team and 2 mines near trees close to the blue team.

This change helps Tinker and Venge to use their abilities with mines much better(but mines still might not spawn in 1v1 or 2v2).

**Comment by DoctorGester** [comment]
I won't rework it that exact way but mine spawning will certainly be fixed so they don't spawn on the same place and don't spawn too close to heroes.
