### ISSUE TITLE
Delete Earth Spirit from game

### ISSUE THREAD

**Issue by 13lackHawk** [DoctorGester/crumbling-island-arena#212]
Im done

**Comment by vocalpocal** [comment]
He is really fucking annoying to deal with his grip and roll, but he still has mediocre winrate (at least in 1v1)

**Comment by vocalpocal** [comment]
I mean he clearly has the cheapest ways to end the game, and you need pretty agressive hero to deal with it

Stall all you can and then roll/grip BrokeBack
