### ISSUE TITLE
rework repulsion + trees

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#214]
1. Убрать то странное отталкивание от деревьев
2. Если человек летит на деревья с большой скоростью то он и дерево получают урон:
1) Урон как по герою так и по дереву может быть больше 1
2) Количество урона зависит от скорости:
I. Как я уже и сказал урон зависит от скорости, взять определённую скорость как за 1 и отнимать хп = кол-ву едениц, после чего человек замедляется в зависимости от полученного урона(те скорость переходит в урон).
II. Если кол-во едениц больше текущего кол-ва хп, то дерево разрушается, а герой продолжает двигаься на оставшейся скорости(Те если герой летел на 8 еденицах, он врезался в фуловое дерево, дерево рушиться, он продолжает двигаться со скоростью 3 еденицы)
III. Если скорость меньше чем нужная чтоб получить еденицу, то она сокращается в меньшую сторону(человек летел со скоростью 3,8 едениц, получил 3 еденицы урона, 0,8 исчезли)
3) Что же взять за еденицу? Думаю сюда очень хорошо подходит отталкивание от ульта траксы.

Основная идея заключается в убирании этого странного отталкивания, остальное-то что по моему мнению должно быть в идеале.

**Comment by DoctorGester** [comment]
Don't really like it, knockbacks and trees will get reworked in some sense but no major changes
