### ISSUE TITLE
Pudge Q + meat

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#234]
Если Q пуджа попало в мясо, то он должен съедать его когда хук вернётся(сейчас он просто ложит его рядом с собой)

**Comment by 13lackHawk** [comment]
Там каждый раз по-разному бывает, иногда он и сразу съедает. Не понял от чего это зависит. Я и от мяса убегал, когда оно на крюке было и к нему бежал, результаты всегда непредсказуемые были.

**Comment by vocalpocal** [comment]
imo the hook shouldn't stop at Meat pieces, but instead gather every piece of meat in his hook like shish-kebab

**Comment by C039ATeJL** [comment]
@13lackHawk Не сказал бы что они такие уж непредсказуемые. Попадаешь хуком(на пути от паджа) по мясу-оно лежит около тебя. Попадаешь хуком(когда он возвращается к паджу) по мясу-оно съедается.

**Comment by 13lackHawk** [comment]
@vocalpocal your idea is very nice. Good player can use ur own meat pieces like a wall against your hooks which is kinda annoying when you're playing Pudge >_<
