### ISSUE TITLE
Sven R can be used after using E before dash start

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#240]
![ga2](https://user-images.githubusercontent.com/29237955/29531134-ddd8a8cc-86af-11e7-9f97-d33b838b03f8.gif)

**Comment by DoctorGester** [comment]
Good, I guess?

**Comment by C039ATeJL** [comment]
Я думал это баг тк после начала E накладывается сайленс.

**Comment by DoctorGester** [comment]
Это ченнелинг. Во время ченнелингов можно юзать инстант абилы.
