### ISSUE TITLE
QoP R+Q heal only 2 hp

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#257]
Хил начинается после первого срабатывания эффекта, также мне кажется что иногда он не работает вообще

**Comment by 13lackHawk** [comment]
Только что проверил в дота2тулс, хил и правда не работает если ульта квопы закончилась. Я как-то забыл на сколько должен хилить даггер. По идее ведь на 3 хп, так?
Насчет первого срабатывания эффекта тоже правда и самое интересное что хил периодически прокает как на 3, так и на 2 и на 1 хп. Даже если ты даешь даггер сразу после ульта, все равно число хила получается какое-то рандомное...
