### ISSUE TITLE
Tinker's portal visual effect stays forever

### ISSUE THREAD

**Issue by 13lackHawk** [DoctorGester/crumbling-island-arena#259]
Если кастануть портал примерно в то время, когда вы уже победили/проиграли и вот-вот появится заставка где стоят герои, то может получится вот это(в центре карты):
![1](https://user-images.githubusercontent.com/26493665/30002454-b086c34c-90b2-11e7-9688-6ca0ca3c9a36.png)

**Comment by C039ATeJL** [comment]
https://github.com/DoctorGester/crumbling-island-arena/issues/23
