### ISSUE TITLE
Custom ground break animations

### ISSUE THREAD

**Issue by vocalpocal** [DoctorGester/crumbling-island-arena#268]
I don't know if this is possible, but in Battlerite what I really liked was the way the target dummies at the beginning of each round died differently depending on what skill destroyed them. Like poison attacks corroded them, burning attacks evaporated them and basic slashes just cut them down.

What I was thinking of was something like SK Q taking "last hit" of a ground piece would break the ground down into sand and dust, which would then fall down.

Maybe a special pass reward? 🤔

**Comment by DoctorGester** [comment]
I don't think I'm ever touching the ground pieces again sadly, since valve broke map compilation in 7.00. And even if I did it would still be very hard to do I think because it would require somehow generating 700 particle snapshots for each piece and then particles.
