### ISSUE TITLE
Lycan Q wolf health sometimes jumps between 1 and 2

### ISSUE THREAD

**Issue by DoctorGester** [DoctorGester/crumbling-island-arena#34]
Need clear steps to reproduce

**Comment by C039ATeJL** [comment]
1.Люкан использует q
2.Волку наносят 1 dmg(до начала анимации атаки)
3.Подставляемся под атаку раненого волка
4.Во время атаки у волка будет отбражаться 2 hp

**Comment by C039ATeJL** [comment]
Хотя сейчас получилось это сделать вообще без атаки волка.Возможно это происходит после определённого пройденного расстояния

**Comment by C039ATeJL** [comment]
Вывод после тестов:
HP обновляется после (определённого) времени существования волков.
