### ISSUE TITLE
Jugg Q applies real silence, preventing from using D when spinning

### ISSUE THREAD

**Issue by DoctorGester** [DoctorGester/crumbling-island-arena#344]
Should apply custom silence + disarm

https://github.com/DoctorGester/crumbling-island-arena/blob/master/game/scripts/vscripts/abilities/jugger/modifier_jugger_q.lua

**Comment by vocalpocal** [comment]
could he do the game pass taunt while spinning if it just added custom silence? 🤔

**Comment by DoctorGester** [comment]
Lol probably yeah
