### ISSUE TITLE
Sub-ability recast doesn't respect animation foreswing

### ISSUE THREAD

**Issue by vocalpocal** [DoctorGester/crumbling-island-arena#356]
If you start re-casting subability at the very end of re-cast timer, your cast is cancelled and nothing happens - if the ability has a cast animation.

My suggestion is that Sub-ability shouldn't be replaced back to base-ability if the hero is casting a spell, but replaced immediately if the ability cast is cancelled.

This bug is most notable with SF

**Comment by 13lackHawk** [comment]
not a bug just a feature lul
u need more practice sf 
git gud

p.s mahou add heal to Q plz i'll gibe u mani for dis (you can even disable damage just add heeeeeeeeealing)

**Comment by vocalpocal** [comment]
LOL where do you need sustain as SF?

**Comment by DoctorGester** [comment]
It's not a feature definitely and I know about it, it's just kind of annoying to fix (you need to detect the ability being cast and somehow prolong the modifier etc etc)
