### ISSUE TITLE
Больше очков людям с ливнувшими тиммейтами в режимах 2v2/3v3

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#38]
Иногда твои тиммейты ливают и начинается неравный бой 1v2/2v3/1v3
Предлагаю давать игрокам с ливнувшими тиммейтами больше очков
(x*(кол-во людей в 1 команде+1)-(количество людей во 2 команде))где x-дефолтное кол-во очков

**Comment by C039ATeJL** [comment]
Не, другая формула:
x*(|t1-t2|+1)
x-дефолтные очки
t1-team 1
t2-team 2

**Comment by 13lackHawk** [comment]
Хорошая идея. Отнимать тоже надо тогда меньше в случае луза.
Еще была идея убирать руну из игры когда ты в меньшинстве, потому что в большинстве всегда легче взять руну чем когда вас меньше. Да и пользы будет больше.

**Comment by C039ATeJL** [comment]
Думаю руну отнимать-лишнее. Мб хилить больше, но отнимать нельзя

**Comment by C039ATeJL** [comment]
Хотя моя позиция-не изменять геймплей, только кол-во получаемых очков

**Comment by 13lackHawk** [comment]
Оу, я вообще думал тут про очки рейтинга разговор.

**Comment by C039ATeJL** [comment]
Если человек победит в соло 2 (2v2) то получит 8 очков, если проиграет в соло 2(2v2) враг получит 7 очков

**Comment by C039ATeJL** [comment]
Если нужно могу дать скрины
Но там не особо понятно

**Comment by C039ATeJL** [comment]
Человек что их делал кривоватенький

**Comment by DoctorGester** [comment]
1v2 win:

1 (умер первым) + 2 (умер вторым) = 3 (двойке)
(3 (остался живым после 2 смертей) + 1 (за победу в команде из 1 игрока)) * (2 (максимум игроков в команде) / 1 (реально игроков в команде)) = 8 (соло игроку)

2v1 win:

2 (умер вторым либо выжил) + 3 (выжил) + 2 (за победу в команде из 2 игроков) = 7 (двойке)
1 (умер первым) * (2 / 1) = 2 (соло игроку)

2v1 win (один игрок из двойки умирает первым):

1 + 3 + 2 = 6 (двойке)
2 * (2 / 1) = 4 (соло игроку)

**Comment by C039ATeJL** [comment]
Мб мвп тогда добавить?
1v2 win

1 (умер первым) + 2 (умер вторым) = 3 (двойке)
(3(остался в живых после 2 смертей)+1(MVP)+1(за победу в команде из 1 игрока)*(2/1)=10

2v1 win

2 (умер вторым либо выжил) + 3 (выжил) + 2 (за победу в команде из 2 игроков)+1(MVP) = 8 (двойке)
1 (умер первым) * (2 / 1) = 2 (соло игроку)

2v1 win (один игрок из двойки умирает первым):

1 + 3 + 2 = 6 (двойке)
(2+1) * (2 / 1) = 6 (соло игроку)

Дело в том, что в большинстве случаев MVP будет именно игрок, что играет 1(Те кто играют в 2 обычно играют агрессивно и ты можешь попадать АОЕ скиллами нанося большое кол-во дмг)

**Comment by DoctorGester** [comment]
Окей
