### ISSUE TITLE
Particle Release Parameter

### ISSUE THREAD

**Issue by dustingraham** [DoctorGester/crumbling-island-arena#404]
https://github.com/DoctorGester/crumbling-island-arena/blob/master/game/scripts/vscripts/level.lua#L275

    for _, particle in ipairs(self.particles) do
        ParticleManager:DestroyParticle(particle, false)
        ParticleManager:ReleaseParticleIndex(0)
    end

Should that be particle instead of 0?

`ParticleManager:ReleaseParticleIndex(particle)`

**Comment by DoctorGester** [comment]
@dustingraham most definitely so! Good catch, thank you
