### ISSUE TITLE
Invoker wears clothes too small for him

### ISSUE THREAD

**Issue by vocalpocal** [DoctorGester/crumbling-island-arena#409]
Or maybe he is just bragging his win in victory screen by wearing baby clothes?

**Comment by vocalpocal** [comment]
![kuva](https://user-images.githubusercontent.com/25270027/61903396-127bc080-af2d-11e9-9d78-85521139a6fc.png)
sorry for no better picture in single player, but he is clearly using his Persona cloak on top of his regular clothes

**Comment by DoctorGester** [comment]
Should be fixed in the latest update, thanks!
