### ISSUE TITLE
Zeus secret skill

### ISSUE THREAD

**Issue by 13lackHawk** [DoctorGester/crumbling-island-arena#45]
# THE RED BOX FROM HELL
Appears after casting Q
![311111111111](https://user-images.githubusercontent.com/26493665/27464971-19c1ee58-57d9-11e7-990d-62327ac962f5.png)

**Comment by C039ATeJL** [comment]
XD

**Comment by C039ATeJL** [comment]
Я думал это рофл такой

**Comment by vocalpocal** [comment]
Zeus renamed as The Devil

**Comment by vocalpocal** [comment]
Is this fixed now by valve?

**Comment by DoctorGester** [comment]
Seems fixed.
