### ISSUE TITLE
"Кровотечение" Ликана

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#46]
Кровотечение Ликана накладывается на предметы, на которые, по идеи, не должно:
1. Ремнанты Earth Spirit
2. Руна
3. Мясо паджа (хотя тут можно понять)
4. (Возможно) Томба

**Comment by C039ATeJL** [comment]
Возможно ещё что -то ещё, но я не помню

**Comment by DoctorGester** [comment]
It's mostly okay. Bleeding will get a slight rework in the future anyway.
