### ISSUE TITLE
Jug sword grab sound effect is broken

### ISSUE THREAD

**Issue by vocalpocal** [DoctorGester/crumbling-island-arena#48]
Plays for a very short time and then stops

**Comment by vocalpocal** [comment]
Actually anything that "Dies" while emmits a sound, the sound gets interrupted really fast. If you break down trees with basic attacks, you will notice the same effect.

**Comment by DoctorGester** [comment]
@vocalpocal any examples of other sounds getting interrupted like that? (except for trees)
