### ISSUE TITLE
Снизить урон M1 джагернаута до 1 (без мейчей)

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#50]
Небольшой нерф джагера.

**Comment by C039ATeJL** [comment]
Ещё мб словосочетание "Собирайте мечи" сделать побольше. Новички не замечают

**Comment by 13lackHawk** [comment]
На весь экран хуле, еще дорожку из пунктира вырисовывать до меча.

**Comment by DoctorGester** [comment]
Лишнее усложнение механики
