### ISSUE TITLE
TA killing heroes wont refresh Blink

### ISSUE THREAD

**Issue by vocalpocal** [DoctorGester/crumbling-island-arena#61]
if enemy blink counter is 2/3 and you kill them with non-boosted basic attack, blink wont be refreshed.

Or last hit 0/3 enemy with Q, or 1/2 with R/break boosted m1...

This isn't apparent in 1v1, but in teams and FFA this thing can be quite annoying.

**Comment by 13lackHawk** [comment]
Same shit with Pudge(intended?).
When you hit an enemy with 3 or lower hp with your m1 and then hit him with Q or W you get no meat drop.
