### ISSUE TITLE
Storm Q

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#66]
Хотелось бы чтоб Q шторма при столкновении с деревом или дыркой не разрушалась, а ставилась.

**Comment by vocalpocal** [comment]
Please fix Tiny Q too!

**Comment by 13lackHawk** [comment]
Оба варианта мне не нравятся. Чисто гипотетически может сложится такая ситуация, что тот же тини будет кидать камень в цель рядом с деревьями, потом сразу подбирать и кидать еще раз. Если камень будет отлетать от деревьев, то в этом тоже ничего хорошего не будет.
Хз какой тогда смысл будет от деревьев, если не полная блокировка большинства скиллшотов.

**Comment by C039ATeJL** [comment]
С Q Tiny понятно(кстати можно было бы просто уменьшить ускорение и сделать его перманентным когда Q в cd) , но что не так с Q шторма? Часто бывают ситуации когда ты играешь против какого-нибудь агрессивного персонажа(по типу траксы), она к тебе приближается и ты ошибаешься на пару пикселей в использовании ремнанта(он разбивается об деревья). Итог-минус большая часть хп или вообще смерть в редких случаях.

**Comment by DoctorGester** [comment]
Should be alright now
