### ISSUE TITLE
Zeus Q, Invo Q и подобные скиллы не используется на область без земли

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#67]
Использование Санстрайка и Болта в "Дыру" не даёт вообще ничего.
P.S. Систему (при которой они не наносят урон если кастануть их в область без земли) думаю лучше оставить, ибо земля может разрушиться за время каста.
P.P.S. Идея в том, чтоб было невозможно начать каст в "дыру".

**Comment by DoctorGester** [comment]
Sadly too hard to implement/generally not worth the effort.
