### ISSUE TITLE
Earth Spirit suggestions

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#68]
M1-cd 0.6 - 0.8;
Q- Земля ломается, но в 2 раза медленней.
W
1.Сила притягивания - 30%;
2.Сила отталкивания - 10%;
3.Притягивание не усиливается Tusk r.
E- проверяет наличие копии под земелей при приземлении а не использовании.
R
1.При использовании даёт щит на 5 hp;
2.Под действием r земеля уязвим к магическому и физическому урону (но не к отталкиваниям, станам, замедлениям и подобным эффектам);
3.При разрушинии щита ульт прерывается;
4.Кд начинается когда заканчивается действие ультимейта;
5.Земля под катящимся земелей не ломается(естественным образом).

**Comment by 13lackHawk** [comment]
> 3.Притягивание не усиливается Tusk r.
Дальше не читал. Слишком сложное усложнение механики.

**Comment by C039ATeJL** [comment]
Конечно, некоторый изменения могу быть отклонены или заменены на что-то другое(по причине усложнения механики или просто ненужности). Я просто сказал что мне хотелось бы чтоб пофиксили/занерфили и в насколько сильно. 
Спорными для меня  были W:3; E ;Q ; R:2; R:4 и R:5(т.к. не разбираюсь в lua и не могу сказать насколько сложна их реализация)
Не включил в список R:1,3 т.к. подобные изменения предлагал Mahou.
Q:1 является не особо важным изменением(за исключением редких ситуаций) и его можно убрать если будет слишком сложно.
R:2 не знаю есть ли в игре такая механика, но это можно убрать сделав земелю уязвимым только к M1(ака щит АМа) и уменьшив силу щита(R:1).
R:4 можно просто увеличить кд.
R:5 ситуация как и с Q:1.
E повтор.
W:3 повтор.
P.S. сейчас перечитывая понял что знак "-" может быть принят за тире, но это минус
