### ISSUE TITLE
Enraged Sven can charge inside Invoker EMP

### ISSUE THREAD

**Issue by vocalpocal** [DoctorGester/crumbling-island-arena#70]
or maybe my eyes are playing tricks on me

**Comment by Chiyukii** [comment]
I think this was already mentioned a couple of months ago, when Invoker EMP got changed. Guess that it is supposed to be like that ... But I am not 100% sure anymore

**Comment by vocalpocal** [comment]
I think it was fixed at some point, so I was pretty surprised to see it again.
Old bugs are good to have in issues as well, just in case we don't forget em.

**Comment by vocalpocal** [comment]
Oh! And do note that casting sven charge in invoker EMP without havingyour ultimate on, will cause EMP activate AND put sven charge to CD.

**Comment by Chiyukii** [comment]
Yes, I clearly remember this from a while ago. Same issue, but seems intended somehow. There was something special about Sven's charge ... Idk how I can explain it

**Comment by vocalpocal** [comment]
@Chiyukii I dunno how it is any different to WR Q for instance, without the ult form I mean.

**Comment by Chiyukii** [comment]
Maybe it has got something to do with the channel(ing time) ? I mean, both channels differ from each other
