### ISSUE TITLE
Evenly distribute spawn places instead of randomly

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#72]
Это может сильно повлиять на игру
Например если пассивный герой(тинкер, снайпер) заспавнится  рядом с агрессивным(урса, тракса)
то это даст большое преимущество агрессивному герою.(или обратная ситуация)

**Comment by vocalpocal** [comment]
+1 for ranked. (Google's translation is very weird, but this thread is about spawning locations, right?)

**Comment by C039ATeJL** [comment]
@vocalpocal  Yes
