### ISSUE TITLE
Заряженная М1 туска отражает снаряды

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#87]

**Comment by 13lackHawk** [comment]
Да что угодно уже дайте ему чтобы отражать снаряды, сейчас за этого героя просто невероятно тяжело и скучно играть(исключение это комбы с кнокбек героями, но до ульты один хер скучно). Ностальгия по 1.0 когда любым скиллом можно было отражать скиллы врага еще осталась :c

**Comment by DoctorGester** [comment]
I don't think this is gonna make him any more viable.
The hero is high on rework priority list either way.
