### ISSUE TITLE
Projectiles reflected by WR W grant kill credit to original projectile owners

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#88]

**Comment by DoctorGester** [comment]
This should actually work properly for most projectiles, which one did you encounter it with?

**Comment by C039ATeJL** [comment]
Q эмбера. Я не уверен что это так работает сейчас(воспоминания о моменте смутные). Решил добавить потому что вспомнил что раньше этот баг существовал и работал со всеми снарядами(может быть).(я не видел его фикса в ченджлогах и не знаю был ли он)

**Comment by vocalpocal** [comment]
reflected WR m1 also provides speed boost to the original owner
