### ISSUE TITLE
Реворк R снайпера

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#93]
1. Ложится, теряет возможность передвигаться. M1 теряет анимацию. R имеет перезарядку, которая начинается когда снайпер встаёт. Длительность R неограниченна;
2. Получает щит на x hp;
3. R заменяется способностью "встать";
4. E заменяется на способность "зарядить бронебойный"(не придумал нормальное название). После задержки выпускает сильный снаряд, наносящий 4(изначально) урона. Разбивает любой снаряд(за каждый разбитый снаряд теряет по 1 дмг). Если урон=0 то исчезает;
5. Земля под лежащим снайпером разрушается медленней(p=F/S).

**Comment by DoctorGester** [comment]
Sniper has to be super simple, like dumb simple, this won't do.
