### ISSUE TITLE
R венги

### ISSUE THREAD

**Issue by C039ATeJL** [DoctorGester/crumbling-island-arena#94]
Добавить возможность рекаста ульты - меняет местами венгу и ультимейт, уничтожает ультимейт.
Зачем?
1. Эскейп.
2. Нападение на врага за деревьями.

**Comment by 13lackHawk** [comment]
Ее ульта и так имба, нужно другие скиллы бафать.

**Comment by C039ATeJL** [comment]
Я просто хз как их можно апнуть

**Comment by C039ATeJL** [comment]
У неё всё хорошо, кроме разрушения деревьев.
90% игр(где люди понимают что делают деревья) за агрессивную венгу доходят до лейта где начинается игра "не ходи по красной земле" из-за того. что враг просто бегал вокруг деревьев всю игру.
P.S. Я говорю только о 1 на 1 так как там нет возможности зайти с 2 сторон.

**Comment by DoctorGester** [comment]
Doesn't sound good to me
